
Data Cleaning and Transformation - [Fifa21_dataset](https://www.kaggle.com/datasets/yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring)

In [387]:
import pandas as pd

Loading dataset

In [388]:
fifa = pd.read_csv('fifa21_raw_data.csv')

C:\Users\Piotr Becela\AppData\Local\Temp\ipykernel_84856\2366955007.py:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  fifa = pd.read_csv('fifa21_raw_data.csv')

In [389]:
fifa.head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

Checking dataset structure

In [390]:
fifa.shape

(18979, 77)

Removing duplicates

In [391]:
fifa.duplicated().sum()

1

In [392]:
fifa.drop_duplicates(inplace=True)

In [393]:
fifa.shape

(18978, 77)

In [394]:
fifa.head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [395]:
fifa.tail()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,Low,1 ★,58,23,26,27,50,48,2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,70,46,40,53,16,40,3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,Medium,1 ★,64,28,26,38,48,51,3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,64,40,48,49,35,45,5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,Medium,1 ★,57,32,43,48,44,49,2

In [396]:
fifa

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,Low,1 ★,58,23,26,27,50,48,2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,70,46,40,53,16,40,3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,Medium,1 ★,64,28,26,38,48,51,3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,64,40,48,49,35,45,5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,Medium,1 ★,57,32,43,48,44,49,2

Checking datatypes

In [397]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18978 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18978 non-null  object
 1   LongName          18978 non-null  object
 2   playerUrl         18978 non-null  object
 3   Nationality       18978 non-null  object
 4   Positions         18978 non-null  object
 5   Name              18978 non-null  object
 6   Age               18978 non-null  int64
 7   ↓OVA              18978 non-null  int64
 8   POT               18978 non-null  int64
 9   Team & Contract   18978 non-null  object
 10  ID                18978 non-null  int64
 11  Height            18978 non-null  object
 12  Weight            18978 non-null  object
 13  foot              18978 non-null  object
 14  BOV               18978 non-null  int64
 15  BP                18978 non-null  object
 16  Growth            18978 non-null  int64
 17  Joined            18978 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18978 non-null  object
 20  Wage              18978 non-null  object
 21  Release Clause    18978 non-null  object
 22  Attacking         18978 non-null  int64
 23  Crossing          18978 non-null  int64
 24  Finishing         18978 non-null  int64
 25  Heading Accuracy  18978 non-null  int64
 26  Short Passing     18978 non-null  int64
 27  Volleys           18978 non-null  int64
 28  Skill             18978 non-null  int64
 29  Dribbling         18978 non-null  int64
 30  Curve             18978 non-null  int64
 31  FK Accuracy       18978 non-null  int64
 32  Long Passing      18978 non-null  int64
 33  Ball Control      18978 non-null  int64
 34  Movement          18978 non-null  int64
 35  Acceleration      18978 non-null  int64
 36  Sprint Speed      18978 non-null  int64
 37  Agility           18978 non-null  int64
 38  Reactions         18978 non-null  int64
 39  Balance           18978 non-null  int64
 40  Power             18978 non-null  int64
 41  Shot Power        18978 non-null  int64
 42  Jumping           18978 non-null  int64
 43  Stamina           18978 non-null  int64
 44  Strength          18978 non-null  int64
 45  Long Shots        18978 non-null  int64
 46  Mentality         18978 non-null  int64
 47  Aggression        18978 non-null  int64
 48  Interceptions     18978 non-null  int64
 49  Positioning       18978 non-null  int64
 50  Vision            18978 non-null  int64
 51  Penalties         18978 non-null  int64
 52  Composure         18978 non-null  int64
 53  Defending         18978 non-null  int64
 54  Marking           18978 non-null  int64
 55  Standing Tackle   18978 non-null  int64
 56  Sliding Tackle    18978 non-null  int64
 57  Goalkeeping       18978 non-null  int64
 58  GK Diving         18978 non-null  int64
 59  GK Handling       18978 non-null  int64
 60  GK Kicking        18978 non-null  int64
 61  GK Positioning    18978 non-null  int64
 62  GK Reflexes       18978 non-null  int64
 63  Total Stats       18978 non-null  int64
 64  Base Stats        18978 non-null  int64
 65  W/F               18978 non-null  object
 66  SM                18978 non-null  object
 67  A/W               18978 non-null  object
 68  D/W               18978 non-null  object
 69  IR                18978 non-null  object
 70  PAC               18978 non-null  int64
 71  SHO               18978 non-null  int64
 72  PAS               18978 non-null  int64
 73  DRI               18978 non-null  int64
 74  DEF               18978 non-null  int64
 75  PHY               18978 non-null  int64
 76  Hits              18978 non-null  object
dtypes: int64(55), object(22)
memory usage: 11.3+ MB

Converting lbs to kg

In [398]:
def w_conv(x):
    x = x.replace("lbs","")
    a = str(round(int(x)*0.453592))
    return a + 'kg'
fifa['Weight'] = fifa['Weight'].map(w_conv)

In [399]:
fifa['Weight']

0        72kg
1        83kg
2        87kg
3        70kg
4        68kg
         ...
18974    70kg
18975    58kg
18976    66kg
18977    65kg
18978    68kg
Name: Weight, Length: 18978, dtype: object

Converting feet to cm

In [400]:
def h_conv(x):
    x = x.replace("'", " ").replace("\"", " ").split()
    a = int(x[0]) * 30.48 + int(x[1]) * 2.54
    end = str(round(a))
    return  end + 'cm'

In [401]:
fifa['Height']=fifa['Height'].map(h_conv)
fifa['Height']

0        170cm
1        188cm
2        188cm
3        180cm
4        175cm
         ...
18974    178cm
18975    170cm
18976    178cm
18977    175cm
18978    175cm
Name: Height, Length: 18978, dtype: object

Transforming Date to Datetime and separating column into year, month and day columns

In [402]:
fifa.Joined = pd.to_datetime(fifa.Joined)

In [403]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18978 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18978 non-null  object
 1   LongName          18978 non-null  object
 2   playerUrl         18978 non-null  object
 3   Nationality       18978 non-null  object
 4   Positions         18978 non-null  object
 5   Name              18978 non-null  object
 6   Age               18978 non-null  int64
 7   ↓OVA              18978 non-null  int64
 8   POT               18978 non-null  int64
 9   Team & Contract   18978 non-null  object
 10  ID                18978 non-null  int64
 11  Height            18978 non-null  object
 12  Weight            18978 non-null  object
 13  foot              18978 non-null  object
 14  BOV               18978 non-null  int64
 15  BP                18978 non-null  object
 16  Growth            18978 non-null  int64
 17  Joined            18978 non-null  datetime64[ns]
 18  Loan Date End     1013 non-null   object
 19  Value             18978 non-null  object
 20  Wage              18978 non-null  object
 21  Release Clause    18978 non-null  object
 22  Attacking         18978 non-null  int64
 23  Crossing          18978 non-null  int64
 24  Finishing         18978 non-null  int64
 25  Heading Accuracy  18978 non-null  int64
 26  Short Passing     18978 non-null  int64
 27  Volleys           18978 non-null  int64
 28  Skill             18978 non-null  int64
 29  Dribbling         18978 non-null  int64
 30  Curve             18978 non-null  int64
 31  FK Accuracy       18978 non-null  int64
 32  Long Passing      18978 non-null  int64
 33  Ball Control      18978 non-null  int64
 34  Movement          18978 non-null  int64
 35  Acceleration      18978 non-null  int64
 36  Sprint Speed      18978 non-null  int64
 37  Agility           18978 non-null  int64
 38  Reactions         18978 non-null  int64
 39  Balance           18978 non-null  int64
 40  Power             18978 non-null  int64
 41  Shot Power        18978 non-null  int64
 42  Jumping           18978 non-null  int64
 43  Stamina           18978 non-null  int64
 44  Strength          18978 non-null  int64
 45  Long Shots        18978 non-null  int64
 46  Mentality         18978 non-null  int64
 47  Aggression        18978 non-null  int64
 48  Interceptions     18978 non-null  int64
 49  Positioning       18978 non-null  int64
 50  Vision            18978 non-null  int64
 51  Penalties         18978 non-null  int64
 52  Composure         18978 non-null  int64
 53  Defending         18978 non-null  int64
 54  Marking           18978 non-null  int64
 55  Standing Tackle   18978 non-null  int64
 56  Sliding Tackle    18978 non-null  int64
 57  Goalkeeping       18978 non-null  int64
 58  GK Diving         18978 non-null  int64
 59  GK Handling       18978 non-null  int64
 60  GK Kicking        18978 non-null  int64
 61  GK Positioning    18978 non-null  int64
 62  GK Reflexes       18978 non-null  int64
 63  Total Stats       18978 non-null  int64
 64  Base Stats        18978 non-null  int64
 65  W/F               18978 non-null  object
 66  SM                18978 non-null  object
 67  A/W               18978 non-null  object
 68  D/W               18978 non-null  object
 69  IR                18978 non-null  object
 70  PAC               18978 non-null  int64
 71  SHO               18978 non-null  int64
 72  PAS               18978 non-null  int64
 73  DRI               18978 non-null  int64
 74  DEF               18978 non-null  int64
 75  PHY               18978 non-null  int64
 76  Hits              18978 non-null  object
dtypes: datetime64[ns](1), int64(55), object(21)
memory usage: 11.3+ MB

In [404]:
fifa['Joined_Y'] = fifa['Joined'].dt.year
fifa['Joined_M'] = fifa['Joined'].dt.month
fifa['Joined_D'] = fifa['Joined'].dt.day

In [405]:
fifa.columns

Index(['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name',
       'Age', '↓OVA', 'POT', 'Team & Contract', 'ID', 'Height', 'Weight',
       'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Joined_Y', 'Joined_M', 'Joined_D'],
      dtype='object')

In [406]:
fifa[['Value', 'Wage', 'Release Clause']]

        Value   Wage Release Clause
0      €67.5M  €560K        €138.4M
1        €46M  €220K         €75.9M
2        €75M  €125K        €159.4M
3        €87M  €370K          €161M
4        €90M  €270K        €166.5M
...       ...    ...            ...
18974    €35K    €1K           €57K
18975    €60K   €500          €165K
18976    €40K    €1K           €70K
18977    €60K   €500          €165K
18978    €60K   €500          €167K

[18978 rows x 3 columns]

Standardizing money values

In [407]:
def standardize(x):
    if isinstance(x, str):
        if x.find('M') != -1:
            return int(float(x.replace('M','').replace('€', '')) * 1000000)
        elif x.find('K') != -1:
            return int(float(x.replace('K', '').replace('€', '')) * 1000)
    else:
        return int(x)

In [408]:
fifa['Value'] = fifa['Value'].map(standardize)
fifa['Wage'] = fifa['Wage'].map(standardize)
fifa['Release Clause'] = fifa['Release Clause'].map(standardize)
fifa[['Value', 'Wage', 'Release Clause']]

            Value      Wage  Release Clause
0      67500000.0  560000.0     138400000.0
1      46000000.0  220000.0      75900000.0
2      75000000.0  125000.0     159400000.0
3      87000000.0  370000.0     161000000.0
4      90000000.0  270000.0     166500000.0
...           ...       ...             ...
18974     35000.0    1000.0         57000.0
18975     60000.0       NaN        165000.0
18976     40000.0    1000.0         70000.0
18977     60000.0       NaN        165000.0
18978     60000.0       NaN        167000.0

[18978 rows x 3 columns]

Removing the newline character from the Hits column

In [409]:
fifa.Hits = fifa.Hits.str.replace('\n', '')

In [410]:
fifa.Hits

0        372
1        344
2         86
3        163
4        273
        ...
18974    NaN
18975    NaN
18976    NaN
18977    NaN
18978    NaN
Name: Hits, Length: 18978, dtype: object

Removing the star character from SM and IR column

In [411]:
fifa.SM = fifa.SM.str.replace('★', '')
fifa.IR = fifa.IR.str.replace('★', '')
fifa[['SM', 'IR']]

      SM  IR
0      4  5
1      5  5
2      1  3
3      4  4
4      5  5
...   ..  ..
18974  2  1
18975  2  1
18976  2  1
18977  2  1
18978  2  1

[18978 rows x 2 columns]

Spliting the Positions column into 3 new columns

In [412]:
fifa[['Position 1', 'Position 2', 'Position 3']] = fifa.Positions.str.split(" ", expand=True)
fifa[['Position 1', 'Position 2', 'Position 3']]

      Position 1 Position 2 Position 3
0             RW         ST         CF
1             ST         LW       None
2             GK       None       None
3            CAM         CM       None
4             LW        CAM       None
...          ...        ...        ...
18974         CB       None       None
18975         ST       None       None
18976         CB       None       None
18977         CM       None       None
18978        CDM       None       None

[18978 rows x 3 columns]

Separating the Team & Contract column into 2 different columns

In [413]:
fifa['Team & Contract'] = fifa['Team & Contract'].str.lstrip('\n').str.rstrip('\n')
fifa[['Team', 'Contract']] = fifa['Team & Contract'].str.split('\n', expand=True)

Removing columns with not interesting data

In [414]:
fifa = fifa.drop(['photoUrl'], axis='columns')
fifa = fifa.drop(['playerUrl'], axis='columns')

Removing duplicated Columns

In [415]:
fifa = fifa.drop(['Joined'], axis='columns')
fifa = fifa.drop(['Team & Contract'], axis='columns')
fifa = fifa.drop(['Positions'], axis='columns')

In [416]:
fifa.head()

,LongName,Nationality,Name,Age,↓OVA,POT,ID,Height,Weight,foot,...,PHY,Hits,Joined_Y,Joined_M,Joined_D,Position 1,Position 2,Position 3,Team,Contract
0,Lionel Messi,Argentina,L. Messi,33,93,93,158023,170cm,72kg,Left,...,65,372,2004,7,1,RW,ST,CF,FC Barcelona,2004 ~ 2021
1,C. Ronaldo dos Santos Aveiro,Portugal,Cristiano Ronaldo,35,92,92,20801,188cm,83kg,Right,...,77,344,2018,7,10,ST,LW,None,Juventus,2018 ~ 2022
2,Jan Oblak,Slovenia,J. Oblak,27,91,93,200389,188cm,87kg,Right,...,90,86,2014,7,16,GK,None,None,Atlético Madrid,2014 ~ 2023
3,Kevin De Bruyne,Belgium,K. De Bruyne,29,91,91,192985,180cm,70kg,Right,...,78,163,2015,8,30,CAM,CM,None,Manchester City,2015 ~ 2023
4,Neymar da Silva Santos Jr.,Brazil,Neymar Jr,28,91,91,190871,175cm,68kg,Right,...,59,273,2017,8,3,LW,CAM,None,Paris Saint-Germain,2017 ~ 2022

Summary information on the non-numeric columns

In [417]:
fifa.describe(include='object')

,LongName,Nationality,Name,Height,Weight,foot,BP,Loan Date End,W/F,SM,A/W,D/W,IR,Hits,Position 1,Position 2,Position 3,Team,Contract
count,18978,18978,18978,18978,18978,18978,18978,1013,18978,18978,18978,18978,18978,16383,18978,9049,2464,18978,18978
unique,18851,164,17919,21,56,2,15,24,5,5,3,3,5,373,15,14,14,714,131
top,Diego Rodríguez,England,J. Rodríguez,183cm,70kg,Right,CB,"Jun 30, 2021",3 ★,2,Medium,Medium,1,1,CB,CM,RM,FC Barcelona,2019 ~ 2021
freq,3,1704,13,2859,1496,14444,3685,770,11694,9142,12700,13955,17628,3216,3277,1516,342,33,1706